image: python:3.10-slim

stages:
  - build
  - test
  - deploy

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
  MAJOR: "1"
  PIPELINE_SEQUENCE: $CI_PIPELINE_IID


before_script:
  - python3 -V
  - pip install poetry
  - poetry -V
  - poetry config virtualenvs.create false
  - poetry install --no-root

build-job:
  stage: build
  script:
    - poetry install --no-root

unit-test-job:
  stage: test
  script:
    - export PYTHONPATH=./app
    - poetry run pytest

lint-test-job:
  stage: test
  script:
    - which flake8
    - poetry run flake8

deploy-gitlab-job:
  image: docker:23.0.1
  stage: deploy
  services:
    - docker:23.0.1-dind

  variables:
    PROJECT_NAME: "python-fastapi-template" # TODO: 프로젝트명에 맞게 수정
    MAJOR: "1"
    PIPELINE_SEQUENCE: $CI_PIPELINE_IID

  before_script:
    - YEAR_WEEK=`date +"%y%U"`
    - SEM_VER=$MAJOR.$YEAR_WEEK.$PIPELINE_SEQUENCE
    - IMAGE_TAG=$CI_REGISTRY_IMAGE/$PROJECT_NAME:$SEM_VER
    - IMAGE_TAG_LATEST=$CI_REGISTRY_IMAGE/$PROJECT_NAME:latest
  script:
    - docker login -u $CI_DEPLOY_USER -p $CI_DEPLOY_PASSWORD $CI_REGISTRY
    - docker build -t $IMAGE_TAG -t $IMAGE_TAG_LATEST .
    - docker push $IMAGE_TAG
    - docker push $IMAGE_TAG_LATEST
  only:
    - main